# Generated by Django 5.2.3 on 2025-06-18 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='借阅时间')),
                ('due_date', models.DateTimeField(verbose_name='应还时间')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('returned', models.BooleanField(default=False, verbose_name='是否已归还')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
