# Generated by Django 5.2.3 on 2025-06-19 11:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('authors', models.CharField(max_length=200, verbose_name='作者')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publisher', models.CharField(max_length=200, verbose_name='出版社')),
                ('publication_date', models.DateField(verbose_name='出版日期')),
                ('introduction', models.TextField(verbose_name='简介')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='封面')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('resource_type', models.CharField(choices=[('book', '电子图书'), ('exam', '试卷资源'), ('textbook', '电子教材')], max_length=10, verbose_name='资源类型')),
                ('file', models.FileField(upload_to='resources/%Y/%m/', verbose_name='资源文件')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='resource_covers/', verbose_name='封面图片')),
                ('author', models.CharField(max_length=200, verbose_name='作者/出版社')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('category', models.CharField(max_length=100, verbose_name='分类')),
                ('tags', models.CharField(blank=True, help_text='使用逗号分隔多个标签', max_length=200, verbose_name='标签')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类编码')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下载时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource', verbose_name='资源')),
            ],
            options={
                'verbose_name': '下载记录',
                'verbose_name_plural': '下载记录',
                'ordering': ['-download_time'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resourcecategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '资源分类',
                'verbose_name_plural': '资源分类',
                'ordering': ['order', 'name'],
            },
        ),
    ]
