# Generated by Django 5.2.3 on 2025-06-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='download_limit',
            field=models.IntegerField(default=10, verbose_name='每日下载限制'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('guest', '访客'), ('registered', '注册用户'), ('admin', '管理员')], default='registered', max_length=10, verbose_name='用户类型'),
        ),
    ]
