# Generated by Django 5.2.3 on 2025-06-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_download_limit_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='download_limit',
            field=models.IntegerField(default=20, verbose_name='每日下载限制'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('registered', '普通用户'), ('admin', '管理员')], default='registered', max_length=10, verbose_name='用户类型'),
        ),
    ]
